### ISSUE TITLE
[Bug] Plugin error, will provide a new release?

### ISSUE THREAD

**Issue by Yurinann** [Imanity-Software/iSpigot-PracticeAddon#3]
```
[14:33:46 ERROR]: Could not pass event KitSelectEvent to ImanityPracticeAddon v1.0-SNAPSHOT
java.lang.NullPointerException: null
        at dev.imanity.knockback.core.KnockbackServiceImpl.getKnockbackByName(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.addon.practice.provider.PracticeProvider.pickKitKnockback(PracticeProvider.java:28) ~[?:?]
        at org.imanity.addon.practice.provider.impl.StrikePracticeProviderImpl$1.onKitSelect(StrikePracticeProviderImpl.java:26) ~[?:?]
        at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
        at ga.strikepractice.battlekit.DefaultBattleKit.giveKitStuff(DefaultBattleKit.java:414) ~[?:?]
        at ga.strikepractice.battlekit.DefaultBattleKit.giveKit(DefaultBattleKit.java:548) ~[?:?]
        at ga.strikepractice.fights.botduel.BotDuel.doStuff(BotDuel.java:112) ~[?:?]
        at ga.strikepractice.fights.botduel.BotDuel.start(BotDuel.java:81) ~[?:?]
        at ga.strikepractice.npc.CombatNPCDifficultyHolder.selectDifficultyAndStart(DifficultySelector.java:97) ~[?:?]
        at ga.strikepractice.npc.DifficultySelector.onClick(DifficultySelector.java:60) ~[?:?]
        at org.imanity.imanityspigot.events.executor.asm.generated.GeneratedEventExecutor209.execute(Unknown Source) ~[?:?]
        at org.imanity.imanityspigot.executor.EventExecutorGenerator.lambda$create$1(EventExecutorGenerator.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1867) ~[?:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:27) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:52) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at org.imanity.imanityspigot.final .cD.run(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cB.executeTask(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cC.executeTask(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cB.executeNext(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.executeNext(SourceFile:1921) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cB.awaitTasks(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.sleepForTick(SourceFile:1894) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:831) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

Imanity Version: 2022.11.1 LTS BUILD 3
StrikePractice Version: 3.7.0
Java Version: 11
ImanityPracticeAddon Version: Last ReleaseRelease

**Comment by Yurinann** [comment]
Sorry my bad that need imanity knockback
